version: "3.7"
services:
  db:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_DB: genshin_calculator
      POSTGRES_USER: 4Tj6BvP9B4aqpwZ6kSWxjk
      POSTGRES_PASSWORD: aRyK7z4QaXhtS2bzUF3E3w
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
    - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
    - "8080:80"
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    links:
    - "db:pgsql-server"

  express:
    build: ./
    depends_on:
    - db
    ports:
      - "80:8000"

volumes:
  db-data:
  pgadmin-data: